import Head from 'next/head';
import Home from '../components/Home';
import Header from '../components/Header';

export default function Index() {
 
  return (
    <div>
      <Head>
        <title>Amazon</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Home />
    </div>
  );
}
